KJLBK/danum-next

src/app/chat/[roomId]/page.jsx
src/app/chat/page.jsx
src/components/chat/RecentMessagesList.jsx
src/components/question/QuestionCommentItem.jsx
src/service/chatService.js

> ex) #이슈번호, #이슈번호
#42 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
다 못끝내긴했는데, 분기점 맞추기 위해 일부 코드들 보냅니다. 잘가라~
먼저 선작업을 해야하는 작업들이 있어 또 채팅기능은 보류됩니다.
- 메인 페이지 스타일 레이아웃 구성.
- 게시판 스타일 레이아웃 구성.
- 미들웨어 구성.
- 메인 페이지 로그인 상태에 따라 처리되는 로직으로 구현

채팅기능 서비스 로직

---

src/app/join/page.jsx
src/app/test/page.jsx
src/components/auth/JoinForm.jsx
src/components/auth/Profile.jsx
src/components/question/QuestionCommentNew.jsx
src/service/authService.js
src/service/questionService.js

> #71 
> uri를 url로 수정하고 사진이 없으면 빈 문자열을 전달하도록 하였습니다.

71 feat profile image upload

---

src/app/questions/[questionId]/page.jsx
src/app/questions/[questionId]/page.module.css
src/app/questions/page.jsx
src/app/questions/page.module.css
src/components/QuillEditor.jsx
src/components/question/QuestionCommentItem.jsx
src/components/question/QuestionCommentItem.module.css
src/components/question/QuestionCommentNew.jsx
src/components/question/QuestionCommentNew.module.css
src/components/question/QuestionItem.jsx
src/components/question/QuestionItem.module.css

#77 
module.css를 활용하여 스타일링을 적용

게시판 관련 페이지 스타일링 구현

---

next.config.mjs
src/app/api/upload/route.js
src/app/questions/new/page.jsx
src/components/Layout/Header.jsx
src/components/auth/GetProfile.jsx
src/service/authService.js

CloudFront와 S3 연동을 통한 이미지 URL 사용 및 프로필 사진 로직 추가

---

src/app/questions/[questionId]/edit/page.jsx
src/app/questions/[questionId]/page.jsx
src/app/questions/[questionId]/page.module.css
src/components/QuillEditor.jsx
src/service/questionService.js

게시판 삭제 및 수정 기능 구현

---

src/app/questions/[questionId]/edit/page.jsx
src/app/questions/[questionId]/edit/page.module.css
src/components/QuillEditor.jsx
src/components/question/QuestionNew.jsx
src/components/question/QuestionNew.module.css

#85 
게시판 생성 수정 페이지 간단하게 디자인을 하였습니다.

게시판 생성 수정 페이지 디자인

---

src/app/questions/[questionId]/page.jsx
src/components/question/QuestionNew.jsx
src/service/chatGPTService.js
src/service/chatService.js
src/service/questionService.js

#87 
JWT 토큰을 localStorage 대신 쿠키에서 가져오도록 변경
localStorage에서 가져오던 것을 tokenService.js의 getAccessToken()을 이용하도록 수정

토큰 가져오는 방식 변경

---

src/components/Layout/Header.jsx
src/components/auth/GetProfile.jsx
src/components/auth/GetProfile.module.css

#98 
프로필 이미지 클릭 시 드롭다운 메뉴를 표시하는 기능을 구현했습니다.
드롭다운 메뉴로는 마이페이지, 로그아웃을 넣었습니다.

드롭다운 기능 구현

---

src/components/auth/GetProfile.jsx

#103 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요
프로필이 존재하지 않을 경우 프로필을 기본 설정 값으로 보여 줄 수 있도록 하였습니다.

프로필이 없을 때 예외 처리

---

src/app/questions/page.jsx
src/components/question/QuestionItem.jsx

게시판이 보이지 않는 문제

---

src/app/map/page.jsx
src/components/auth/JoinForm.jsx

#109 
회원가입 시 변환된 주소 값을 넘겨주도록 하였습니다.
들여쓰기가 달라져서 바뀐 값이 많은데 55번 줄에 주소 값 추가로 넘겨주는 게 포인트입니다~

회원가입 시 주소 값 추가

---

src/app/map/page.jsx
src/app/questions/page.jsx
src/components/auth/JoinForm.jsx
src/components/question/QuestionItem.jsx

- /q/[qid]/page.jsx에 있는 코드 더미들을 컴포넌트화하여 분리 완료
- PostInfoPanel, QuillViewer 컴포넌트를 생성하여 코드 모듈화
- 공통 모달 컴포넌트 추가 및 관련 CSS 파일 업데이트
- 아직 댓글 관련 코드 더미는 정리되지 않았으며, 이후 추가적인 리팩토링 필요

🔨 chore: merge branch '106-chat-state-with-react-query' into 'main'

---

src/app/questions/[questionId]/page.jsx
src/hooks/commentSelect.js

채택 기능 로직 분리

---

src/app/test/page.jsx
src/components/chat/AuthorChatButton.jsx
src/components/question/view/PostInfoPanel.jsx
src/hooks/useChatMutations.js
src/hooks/useChatQueries.js
src/middleware.js
src/services/authService.js
src/services/chatService.js

1. **AuthorChatButton 추가 및 개선**
- 게시물 작성자와 채팅할 수 있는 AuthorChatButton을 추가했습니다.
- 기존에 `userName`만 전달하던 로직을 수정하여 `userName`과 `userId` 둘 다 전달하도록 변경했습니다.
- 리액트 쿼리를 사용하여 다른 유저와의 1대1 채팅 시 방 번호를 받아오는 로직을 구현했습니다.
2. **PostInfoPanel 및 QuillViewer 컴포넌트 수정**
- AuthorChatButton 추가에 따른 PostInfoPanel과 QuillViewer의 일부 로직을 수정했습니다.
3. **authService 엔드포인트 오류 수정**
- middleware.js에서 authService의 엔드포인트 관련 오류를 수정하였습니다.
4. **리액트 쿼리 적용**
- useChatMutations와 useChatQueries 파일을 생성하여 채팅 관련 로직을 리액트 쿼리로 전환했습니다.
- 기능 구현에 따라 일부 파일이 추가 및 수정되었습니다.
- 이 PR은 AuthorChatButton 기능 개선 및 채팅 기능 로직 전환을 목적으로 합니다.

✨ 채팅 기능 개선 및 AuthorChatButton 기능 추가

---

src/app/chat/[roomId]/page.jsx
src/components/chat/AuthorChatButton.jsx
src/services/authService.js
src/services/chatService.js

- tokenService에서 getAccessToken 함수를 import하여 추가
- localStorage.getItem('accessToken')을 getAccessToken()으로 대체하여 액세스 토큰을 가져오도록 수정

feat(chat): ChatRoomPage 로직 일부 수정 #124

---

src/components/board/buttons/LikeButton.jsx
src/components/board/buttons/LikeButton.module.css
src/components/board/view/PostInfoPanel.jsx
src/services/questionService.js
src/services/villageService.js

#132 
게시물에 좋아요를 할 수 있는 기능을 구현하였습니다.

게시글 좋아요 기능

---

src/app/questions/[questionId]/page.jsx
src/components/board/view/QuillViewer.jsx
src/services/chatGPTService.js

#134 
chatGPT 추가 질문 기능(게시글 작성자만 가능)

chatGPT 추가 질문 기능 구현

---

src/components/Layout/Header.jsx

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
빌드 중 경로 문제가 발생했는데 해결하려고 하였습니다.

빌드 중 경로 문제 해결

---

src/components/common/notificationItem.module.css

fix: 경로 오류 수정

---

src/app/questions/[questionId]/page.jsx
src/app/villages/[villageId]/page.jsx
src/app/villages/new/page.jsx
src/components/board/view/CommentItem.jsx
src/components/board/view/PostInfoPanel.jsx

> ex) #이슈번호, #이슈번호
authStore에서 받아오는 변수명을 수정하였습니다.

authStore 변수명 수정

---

src/app/notifications/page.jsx
src/components/Layout/Header.jsx
src/components/Layout/Header/NotificationsIcon.jsx

#150 
알림 개수를 로그인 하지 않아도 조회하는 버그를 수정하였습니다.
알림창에서 채팅으로 페이지 전환을 할 때 경로 이슈를 수정하였습니다.

알림창 예외 처리 및 버그 수정
